version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
    
  frontend:
    image: 385626522460.dkr.ecr.us-east-2.amazonaws.com/pianco/frontend:latest
    restart: always
    
  backend:
    image: 385626522460.dkr.ecr.us-east-2.amazonaws.com/pianco/backend:latest
    ports:
      - "11088:11088"
    restart: always
    environment:
      - PORT=11088
